#!/bin/sh

# Ładowanie zasobów i ustawienie tła
xrdb $HOME/.Xresources
xsetroot -solid grey

# Wyłączenie problematycznych mapowań (opcjonalne)
export XKL_XMODMAP_DISABLE=1

# Uruchomienie emulatora terminala (opcjonalnie, odkomentuj jeśli chcesz)
# x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &

xsetroot -cursor_name left_ptr

# Kluczowa zmiana: Uruchomienie Openbox
exec openbox-session

