[global]
 miner = 
 interval = 1

[block]
 full_text = ├─ 
 color = #268bd2
 background = #002b36
 separator = false
 separator_block_width = 2

[block]
 full_text = APT
 command = apt-get upgrade -s 2>/dev/null | grep -c ^Inst || echo -
 color = #859900
 interval = 3600

[block]
 full_text = CP
 command = cat /proc/loadavg | cut -d" " -f1
 color = #b58900
 interval = 5

[block]
 full_text = MEM
 command = free -m | awk '/Mem:/ {print $3"MB"}'
 color = #2aa198
 interval = 10

[block]
 full_text = DISK
 command = df -h / | awk 'NR==2 {print $3}'
 color = #d33682
 interval = 30

[block]
 full_text = VOL
 command = amixer sget Master | awk 'NR==6 {print $2}' | tr -d '[]%'
 color = #6c71c4
 interval = 2

[block]
 full_text = WIFI
 command = wifi | awk '{print $3}'
 color = #859900
 interval = 5

[block]
 full_text = BAT
 command = cat /sys/class/power_supply/BAT1/capacity 2>/dev/null || echo 100
 color = #b58900
 interval = 30

[block]
 full_text = ├─ 
 color = #268bd2
 background = #002b36
 separator = false
 separator_block_width = 2

[block]
 format = %a-%m-% %S:%M:%H 
 color = #859900
 interval = 1
