#!/bin/sh

# Ładowanie zasobów i ustawienie tła
xrdb $HOME/.Xresources
xsetroot -solid grey

# Wyłączenie problematycznych mapowań (opcjonalne)
export XKL_XMODMAP_DISABLE=1

# Ustawienie kursora
xsetroot -cursor_name left_ptr

# Kluczowa zmiana: Uruchomienie i3
exec i3

